version: '3.8'

services:
  backend:
    build:
      context: ./food
      dockerfile: Dockerfile
    container_name: food-rescue-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - food-rescue-network
    restart: unless-stopped

  frontend:
    build:
      context: ./food-frontend
      dockerfile: Dockerfile
    container_name: food-rescue-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - food-rescue-network
    restart: unless-stopped

networks:
  food-rescue-network:
    driver: bridge